USE JEWELRYAUCTIONSYSTEM
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Bracelet')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Brooch')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Earrings')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Loose Stone')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Misc')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Necklace')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Pendant')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Ring')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Set')
INSERT INTO CATEGORY (CATEGORYNAME) VALUES (N'Watch')
select * from CATEGORY